version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      
    volumes:
      - ../..:/workspaces:cache
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    environment:
      FLYWAY_URL: 'jdbc:postgresql://localhost:5432/platform'
      FLYWAY_USER: admin
      FLYWAY_PASSWORD: postgres_admin_dev
      FLYWAY_DEFAULT_SCHEMA: flyway
      FLYWAY_SCHEMAS: 'public,flyway'
      FLYWAY_LOCATIONS: 'filesystem:/workspaces/postgraphile_repro/flyway'

  db:
    build:
      #context: ./images/database
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    volumes:
      - postgraphile-repro-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres_dev
      POSTGRES_USER: postgres
      POSTGRES_DB: platform
      ADMIN_PASSWORD: postgres_admin_dev

volumes:
  postgraphile-repro-data:
