CREATE TYPE pad_type AS ENUM('MOBILE', 'STATIC', 'TEMPORARY');
CREATE TYPE launch_pad AS (id BIGINT, type pad_type);

-- DROP TABLE IF EXISTS mobile_pad;
CREATE TABLE mobile_pad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    time_to_reach_in_hours NUMERIC DEFAULT 10
);

-- DROP TABLE IF EXISTS static_pad;
CREATE TABLE static_pad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    time_to_reach_in_hours NUMERIC DEFAULT 5
);

-- DROP TABLE IF EXISTS temp_pad;
create TABLE temp_pad (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    time_to_reach_in_hours NUMERIC DEFAULT 15
);

-- DROP TABLE IF EXISTS spacecraft;
CREATE TABLE IF NOT EXISTS spacecraft (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    return_to_earth TSRANGE NOT NULL
);


-- DROP FUNCTION spacecraft_eta;
CREATE OR REPLACE FUNCTION spacecraft_eta(
    spacecraft spacecraft,
    "to" launch_pad
) RETURNS TSRANGE LANGUAGE plpgsql STABLE 
AS $$
BEGIN
    RETURN $1.return_to_earth;
END $$;


GRANT SELECT ON spacecraft TO "server";